import Head from 'next/head'
import Link from 'next/link';
import Nav from '../planets/Nav';
import React, {useState} from 'react';

export default function Home(props) {
  const [currentPlanet, setcurrentPlanet] = useState(props.planets.earth);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >

        {props.planets.earth}
       

      </main>

      
    </div>
  )
}
