import Head from 'next/head'
import Link from 'next/link';
import Nav from '../planets/Nav';


export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >

            {props.planets.venus}
       <Nav />
      </main>

      
    </div>
  )
}
